"""
Training loops for GNN (supervised) and DQN (reinforcement learning).

Supervised GNN Training:
    1. Generate training data by running SimPy with random traffic
    2. Compute Dijkstra-optimal next-hop labels on congestion-weighted graphs
    3. Train GraphSAGE + routing head with cross-entropy loss

DQN Training:
    1. Use pretrained GNN encoder (frozen or jointly trained)
    2. Train DQN on SimPy environment with GRL reward function
    3. Prioritised Experience Replay for sample efficiency
"""

from __future__ import annotations

import copy
import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

from src.models.graphsage import GNNRoutingModel, GraphSAGEEncoder
from src.sim.torus_graph import TorusGraph, DIRECTION_VECTORS
from src.sim.traffic import TrafficGenerator
from src.sim.simulator import TorusSimulator
from src.routers.xy_router import XYRouter
from src.utils.logging import get_logger
from src.utils.seeding import set_global_seed

logger = get_logger("models.training")

# Direction index mapping
DIRECTION_TO_IDX = {"N": 0, "S": 1, "E": 2, "W": 3}
IDX_TO_DIRECTION = {v: k for k, v in DIRECTION_TO_IDX.items()}


# ============================================================
# Training Data Generation
# ============================================================

class RoutingDataset(Dataset):
    """Dataset of (graph_state, current_node, dst_node, optimal_direction) tuples.

    Generated by running the simulator and computing Dijkstra-optimal
    next-hop directions on the live congestion-weighted graph.
    """

    def __init__(
        self,
        node_features_list: List[torch.Tensor],
        edge_index_list: List[torch.Tensor],
        current_indices: List[torch.Tensor],
        dst_indices: List[torch.Tensor],
        labels: List[torch.Tensor],
    ):
        self.node_features_list = node_features_list
        self.edge_index_list = edge_index_list
        self.current_indices = current_indices
        self.dst_indices = dst_indices
        self.labels = labels

    def __len__(self) -> int:
        return len(self.labels)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        return {
            "node_features": self.node_features_list[idx],
            "edge_index": self.edge_index_list[idx],
            "current_indices": self.current_indices[idx],
            "dst_indices": self.dst_indices[idx],
            "labels": self.labels[idx],
        }


def generate_training_data(
    grid_size: int,
    num_snapshots: int = 500,
    injection_rate: float = 0.01,
    sim_duration_ns: float = 5000,
    seed: int = 42,
    samples_per_snapshot: int = 20,
) -> Tuple[List[torch.Tensor], List[torch.Tensor], List[torch.Tensor], List[torch.Tensor], List[torch.Tensor]]:
    """Generate supervised training data from simulator snapshots.

    For each snapshot:
        1. Run simulator briefly to build up congestion
        2. Capture graph state
        3. For random (src, dst) pairs, compute Dijkstra optimal next-hop
        4. Store (graph, src_idx, dst_idx, optimal_direction)

    Args:
        grid_size: Torus size N for N×N.
        num_snapshots: Number of graph snapshots to generate.
        injection_rate: Traffic injection rate.
        sim_duration_ns: How long to run each snapshot simulation.
        seed: Random seed.
        samples_per_snapshot: Number of (src, dst) routing decisions per snapshot.

    Returns:
        (node_features_list, edge_index_list, current_indices, dst_indices, labels)
    """
    logger.info(
        f"Generating training data: grid={grid_size}, "
        f"snapshots={num_snapshots}, samples/snap={samples_per_snapshot}"
    )

    rng = np.random.default_rng(seed)

    node_features_list = []
    edge_index_list = []
    current_indices_list = []
    dst_indices_list = []
    labels_list = []

    all_nodes = [(x, y) for x in range(grid_size) for y in range(grid_size)]

    for snap_idx in range(num_snapshots):
        # Build fresh torus and simulate to create congestion patterns
        snap_seed = seed + snap_idx
        set_global_seed(snap_seed)

        torus = TorusGraph(grid_size)

        # Optionally inject some failures for diversity
        if rng.random() < 0.3:
            failure_rate = rng.uniform(0.02, 0.15)
            torus.inject_link_failures(failure_rate, np.random.default_rng(snap_seed))

        # Run a short simulation to build up congestion
        router = XYRouter()
        sim = TorusSimulator(
            torus, router,
            duration_ns=sim_duration_ns,
            warmup_ns=0,
        )
        traffic_gen = TrafficGenerator(
            pattern="uniform" if rng.random() < 0.5 else "hotspot",
            grid_size=grid_size,
            injection_rate=injection_rate,
            seed=snap_seed,
        )
        sim.run(traffic_gen)

        # Capture graph state
        state = torus.get_graph_state()
        node_features = torch.tensor(state["node_features"], dtype=torch.float32)
        edge_index = torch.tensor(state["edge_index"], dtype=torch.long)
        coord_to_idx = state["coord_to_idx"]

        # Sample (current, dst) pairs and compute optimal next-hop
        current_indices = []
        dst_indices = []
        labels = []

        active_nodes = torus.get_active_nodes()
        if len(active_nodes) < 2:
            continue

        for _ in range(samples_per_snapshot):
            # Random current and destination
            pair_indices = rng.choice(len(active_nodes), size=2, replace=False)
            current_node = active_nodes[pair_indices[0]]
            dst_node = active_nodes[pair_indices[1]]

            # Get optimal next-hop via Dijkstra
            optimal_dir = torus.get_optimal_next_hop(current_node, dst_node)

            if optimal_dir is None:
                continue

            if optimal_dir not in DIRECTION_TO_IDX:
                continue

            current_indices.append(coord_to_idx[current_node])
            dst_indices.append(coord_to_idx[dst_node])
            labels.append(DIRECTION_TO_IDX[optimal_dir])

        if len(labels) == 0:
            continue

        node_features_list.append(node_features)
        edge_index_list.append(edge_index)
        current_indices_list.append(torch.tensor(current_indices, dtype=torch.long))
        dst_indices_list.append(torch.tensor(dst_indices, dtype=torch.long))
        labels_list.append(torch.tensor(labels, dtype=torch.long))

        if (snap_idx + 1) % 100 == 0:
            logger.info(f"  Generated {snap_idx + 1}/{num_snapshots} snapshots")

    logger.info(
        f"Data generation complete: {len(labels_list)} usable snapshots, "
        f"~{sum(len(l) for l in labels_list)} total samples"
    )

    return node_features_list, edge_index_list, current_indices_list, dst_indices_list, labels_list


# ============================================================
# Supervised GNN Training
# ============================================================

def train_gnn_supervised(
    grid_size: int = 8,
    num_snapshots: int = 500,
    epochs: int = 100,
    lr: float = 1e-3,
    weight_decay: float = 1e-4,
    batch_size: int = 32,
    patience: int = 10,
    device: str = "cpu",
    checkpoint_dir: str = "results/checkpoints",
    seed: int = 42,
    samples_per_snapshot: int = 20,
    log_dir: Optional[str] = "results/logs",
) -> Dict[str, Any]:
    """Train the GNN routing model with supervised learning.

    Args:
        grid_size: Torus N for N×N.
        num_snapshots: Number of training snapshots.
        epochs: Maximum training epochs.
        lr: Learning rate.
        weight_decay: L2 regularisation.
        batch_size: Not used for graph-level batching (1 graph at a time).
        patience: Early stopping patience.
        device: 'cpu' or 'cuda'.
        checkpoint_dir: Where to save model checkpoints.
        seed: Random seed.
        samples_per_snapshot: Routing samples per graph snapshot.
        log_dir: TensorBoard log directory.

    Returns:
        Dict with training history and best metrics.
    """
    set_global_seed(seed)

    logger.info(f"Starting supervised GNN training on {grid_size}x{grid_size} torus")
    logger.info(f"Device: {device}, LR: {lr}, Epochs: {epochs}, Patience: {patience}")

    # TensorBoard setup
    writer = None
    if log_dir:
        try:
            from torch.utils.tensorboard import SummaryWriter
            log_path = os.path.join(log_dir, f"gnn_supervised_{grid_size}x{grid_size}")
            writer = SummaryWriter(log_path)
            logger.info(f"TensorBoard logging to: {log_path}")
        except ImportError:
            logger.warning("TensorBoard not available, skipping logging")

    # Generate training data
    data = generate_training_data(
        grid_size=grid_size,
        num_snapshots=num_snapshots,
        seed=seed,
        samples_per_snapshot=samples_per_snapshot,
    )
    node_features_list, edge_index_list, current_indices, dst_indices, labels = data

    total_samples = len(labels)
    if total_samples == 0:
        raise ValueError("No training data generated!")

    # Split: 80% train, 10% val, 10% test
    n_train = int(0.8 * total_samples)
    n_val = int(0.1 * total_samples)

    indices = list(range(total_samples))
    rng = np.random.default_rng(seed)
    rng.shuffle(indices)

    train_indices = indices[:n_train]
    val_indices = indices[n_train : n_train + n_val]
    test_indices = indices[n_train + n_val :]

    logger.info(f"Data split: train={len(train_indices)}, val={len(val_indices)}, test={len(test_indices)}")

    # Model
    model = GNNRoutingModel(
        in_channels=8,
        hidden_channels=128,
        embedding_dim=64,
        num_layers=3,
        num_directions=4,
        dropout=0.1,
    ).to(device)

    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    logger.info(f"Model: {total_params} total params, {trainable_params} trainable")

    # Optimizer with cosine annealing
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    criterion = nn.CrossEntropyLoss()

    # Training loop
    best_val_loss = float("inf")
    best_val_acc = 0.0
    patience_counter = 0
    history = {
        "train_loss": [],
        "val_loss": [],
        "val_acc": [],
        "lr": [],
    }

    checkpoint_path = Path(checkpoint_dir)
    checkpoint_path.mkdir(parents=True, exist_ok=True)
    best_model_path = checkpoint_path / f"gnn_best_{grid_size}x{grid_size}.pt"

    start_time = time.time()

    for epoch in range(epochs):
        # --- Train ---
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        rng.shuffle(train_indices)

        for idx in train_indices:
            nf = node_features_list[idx].to(device)
            ei = edge_index_list[idx].to(device)
            ci = current_indices[idx].to(device)
            di = dst_indices[idx].to(device)
            lab = labels[idx].to(device)

            optimizer.zero_grad()
            logits = model(nf, ei, ci, di)
            loss = criterion(logits, lab)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            train_loss += loss.item() * len(lab)
            train_correct += (logits.argmax(dim=-1) == lab).sum().item()
            train_total += len(lab)

        avg_train_loss = train_loss / max(train_total, 1)
        train_acc = train_correct / max(train_total, 1)

        # --- Validate ---
        model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for idx in val_indices:
                nf = node_features_list[idx].to(device)
                ei = edge_index_list[idx].to(device)
                ci = current_indices[idx].to(device)
                di = dst_indices[idx].to(device)
                lab = labels[idx].to(device)

                logits = model(nf, ei, ci, di)
                loss = criterion(logits, lab)

                val_loss += loss.item() * len(lab)
                val_correct += (logits.argmax(dim=-1) == lab).sum().item()
                val_total += len(lab)

        avg_val_loss = val_loss / max(val_total, 1)
        val_acc = val_correct / max(val_total, 1)

        scheduler.step()
        current_lr = scheduler.get_last_lr()[0]

        # Record history
        history["train_loss"].append(avg_train_loss)
        history["val_loss"].append(avg_val_loss)
        history["val_acc"].append(val_acc)
        history["lr"].append(current_lr)

        # TensorBoard logging
        if writer:
            writer.add_scalar("Loss/train", avg_train_loss, epoch)
            writer.add_scalar("Loss/val", avg_val_loss, epoch)
            writer.add_scalar("Accuracy/train", train_acc, epoch)
            writer.add_scalar("Accuracy/val", val_acc, epoch)
            writer.add_scalar("LR", current_lr, epoch)

        # Early stopping check
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            best_val_acc = val_acc
            patience_counter = 0

            # Save best model
            torch.save({
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "val_loss": avg_val_loss,
                "val_acc": val_acc,
                "grid_size": grid_size,
                "config": {
                    "in_channels": 8,
                    "hidden_channels": 128,
                    "embedding_dim": 64,
                    "num_layers": 3,
                },
            }, best_model_path)
        else:
            patience_counter += 1

        if (epoch + 1) % 10 == 0 or patience_counter == 0:
            logger.info(
                f"Epoch {epoch+1:3d}/{epochs}: "
                f"train_loss={avg_train_loss:.4f}, "
                f"val_loss={avg_val_loss:.4f}, "
                f"val_acc={val_acc:.4f}, "
                f"lr={current_lr:.6f}, "
                f"patience={patience_counter}/{patience}"
            )

        if patience_counter >= patience:
            logger.info(f"Early stopping at epoch {epoch+1}")
            break

    elapsed = time.time() - start_time

    # --- Test ---
    model.eval()
    test_correct = 0
    test_total = 0

    with torch.no_grad():
        for idx in test_indices:
            nf = node_features_list[idx].to(device)
            ei = edge_index_list[idx].to(device)
            ci = current_indices[idx].to(device)
            di = dst_indices[idx].to(device)
            lab = labels[idx].to(device)

            logits = model(nf, ei, ci, di)
            test_correct += (logits.argmax(dim=-1) == lab).sum().item()
            test_total += len(lab)

    test_acc = test_correct / max(test_total, 1)

    if writer:
        writer.add_scalar("Accuracy/test", test_acc, epochs)
        writer.close()

    logger.info(
        f"Training complete in {elapsed:.1f}s: "
        f"best_val_loss={best_val_loss:.4f}, "
        f"best_val_acc={best_val_acc:.4f}, "
        f"test_acc={test_acc:.4f}"
    )
    logger.info(f"Best model saved to: {best_model_path}")

    return {
        "best_val_loss": best_val_loss,
        "best_val_acc": best_val_acc,
        "test_acc": test_acc,
        "epochs_trained": len(history["train_loss"]),
        "total_params": total_params,
        "training_time_s": elapsed,
        "checkpoint_path": str(best_model_path),
        "history": history,
    }


# ============================================================
# DQN Reinforcement Learning Training
# ============================================================

# Action index mapping for DQN (includes Hold)
ACTION_TO_DIRECTION = {0: "N", 1: "S", 2: "E", 3: "W", 4: "HOLD"}


def _compute_reward(
    packet_delivered: bool,
    packet_dropped: bool,
    hop_delay_ns: float,
    prev_utilisation: float,
    curr_utilisation: float,
    alpha_drop: float = 10.0,
    beta_util: float = 0.5,
) -> float:
    """Compute the GRL reward signal.

    Reward = -hop_latency/100 - alpha*drop + beta*(prev_util - curr_util)

    Args:
        packet_delivered: True if packet reached destination this step.
        packet_dropped: True if packet was dropped this step.
        hop_delay_ns: Transmission + propagation delay for this hop.
        prev_utilisation: Link utilisation before this step.
        curr_utilisation: Link utilisation after this step.
        alpha_drop: Penalty multiplier for packet drops.
        beta_util: Reward coefficient for utilisation improvement.

    Returns:
        Scalar reward value.
    """
    reward = 0.0

    if packet_delivered:
        reward += 1.0  # Delivery bonus

    if packet_dropped:
        reward -= alpha_drop

    # Latency penalty (normalised)
    reward -= hop_delay_ns / 100.0

    # Utilisation improvement reward
    util_delta = prev_utilisation - curr_utilisation
    reward += beta_util * util_delta

    return reward


def _build_dqn_state(
    gnn_encoder: GraphSAGEEncoder,
    node_features: torch.Tensor,
    edge_index: torch.Tensor,
    current_node_idx: int,
    packet_src: tuple,
    packet_dst: tuple,
    hops_so_far: int,
    grid_size: int,
    device: str = "cpu",
    cached_embeddings: Optional[torch.Tensor] = None,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Build the 69-dim DQN state vector from graph + packet features.

    Returns:
        (state_vector [69], embeddings [num_nodes, 64]) — embeddings cached.
    """
    if cached_embeddings is None:
        with torch.no_grad():
            cached_embeddings = gnn_encoder(node_features, edge_index)

    node_emb = cached_embeddings[current_node_idx]  # [64]

    n = max(grid_size - 1, 1)
    packet_features = torch.tensor(
        [
            packet_src[0] / n,
            packet_src[1] / n,
            packet_dst[0] / n,
            packet_dst[1] / n,
            min(hops_so_far / (4 * grid_size), 1.0),
        ],
        dtype=torch.float32,
        device=device,
    )

    state = torch.cat([node_emb, packet_features])  # [69]
    return state, cached_embeddings


def train_dqn(
    grid_size: int = 4,
    gnn_checkpoint_path: Optional[str] = None,
    freeze_gnn: bool = True,
    episodes: int = 500,
    lr: float = 1e-3,
    gamma: float = 0.99,
    replay_capacity: int = 50_000,
    batch_size: int = 64,
    target_update_freq: int = 200,
    eps_start: float = 1.0,
    eps_end: float = 0.05,
    eps_decay_steps: int = 5000,
    alpha_drop: float = 10.0,
    beta_util: float = 0.5,
    device: str = "cpu",
    checkpoint_dir: str = "results/checkpoints",
    seed: int = 42,
    log_dir: Optional[str] = "results/logs",
    gnn_lr_joint: float = 1e-4,
    injection_rate: float = 0.01,
    sim_duration_ns: float = 5000,
) -> Dict[str, Any]:
    """Train DQN routing policy with reinforcement learning.

    Supports two modes:
        - freeze_gnn=True: GNN encoder frozen, only DQN weights updated
        - freeze_gnn=False: Joint training of GNN encoder + DQN policy

    The training loop:
        1. For each episode, create a fresh torus + traffic
        2. Inject packets and route them with epsilon-greedy DQN
        3. Collect (s, a, r, s', done) transitions in PER buffer
        4. Sample mini-batches and update DQN via TD-error
        5. Periodically hard-update target network

    Args:
        grid_size: Torus N for N×N.
        gnn_checkpoint_path: Path to pretrained GNN checkpoint (None → random init).
        freeze_gnn: If True, GNN encoder weights are frozen.
        episodes: Number of training episodes.
        lr: DQN learning rate.
        gamma: Discount factor.
        replay_capacity: PER buffer size.
        batch_size: Mini-batch size for DQN updates.
        target_update_freq: Steps between target network hard updates.
        eps_start: Initial epsilon for exploration.
        eps_end: Final epsilon.
        eps_decay_steps: Steps to decay epsilon linearly.
        alpha_drop: Drop penalty coefficient.
        beta_util: Utilisation reward coefficient.
        device: 'cpu' or 'cuda'.
        checkpoint_dir: Checkpoint save directory.
        seed: Random seed.
        log_dir: TensorBoard log directory.
        gnn_lr_joint: Learning rate for GNN in joint training mode.
        injection_rate: Traffic injection rate per episode.
        sim_duration_ns: Simulation duration per episode.

    Returns:
        Dict with training metrics and checkpoint path.
    """
    from src.models.dqn import DuelingDQN
    from src.models.replay_buffer import PrioritizedReplayBuffer

    set_global_seed(seed)

    mode_str = "frozen-GNN" if freeze_gnn else "joint-training"
    logger.info(f"Starting DQN training ({mode_str}) on {grid_size}x{grid_size} torus")
    logger.info(f"Device: {device}, LR: {lr}, Episodes: {episodes}, Gamma: {gamma}")

    # TensorBoard
    writer = None
    if log_dir:
        try:
            from torch.utils.tensorboard import SummaryWriter
            tag = "frozen" if freeze_gnn else "joint"
            log_path = os.path.join(log_dir, f"dqn_{tag}_{grid_size}x{grid_size}")
            writer = SummaryWriter(log_path)
        except ImportError:
            pass

    # --- Load GNN encoder ---
    if gnn_checkpoint_path and os.path.exists(gnn_checkpoint_path):
        checkpoint = torch.load(gnn_checkpoint_path, map_location=device, weights_only=False)
        config = checkpoint.get("config", {})
        gnn_model = GNNRoutingModel(
            in_channels=config.get("in_channels", 8),
            hidden_channels=config.get("hidden_channels", 128),
            embedding_dim=config.get("embedding_dim", 64),
            num_layers=config.get("num_layers", 3),
        )
        gnn_model.load_state_dict(checkpoint["model_state_dict"])
        gnn_encoder = gnn_model.encoder.to(device)
        embedding_dim = config.get("embedding_dim", 64)
        logger.info(f"Loaded pretrained GNN from {gnn_checkpoint_path}")
    else:
        embedding_dim = 64
        gnn_encoder = GraphSAGEEncoder(
            in_channels=8, hidden_channels=128,
            out_channels=embedding_dim, num_layers=3,
        ).to(device)
        logger.info("Using randomly initialised GNN encoder")

    if freeze_gnn:
        gnn_encoder.eval()
        for param in gnn_encoder.parameters():
            param.requires_grad = False
        logger.info("GNN encoder weights frozen")
    else:
        gnn_encoder.train()

    # --- DQN networks ---
    state_dim = embedding_dim + 5  # 64 + 5 packet features = 69
    action_dim = 5  # N, S, E, W, Hold

    policy_net = DuelingDQN(state_dim=state_dim, action_dim=action_dim).to(device)
    target_net = DuelingDQN(state_dim=state_dim, action_dim=action_dim).to(device)
    target_net.load_state_dict(policy_net.state_dict())
    target_net.eval()

    # --- Optimiser ---
    if freeze_gnn:
        optimizer = optim.Adam(policy_net.parameters(), lr=lr)
    else:
        optimizer = optim.Adam([
            {"params": policy_net.parameters(), "lr": lr},
            {"params": gnn_encoder.parameters(), "lr": gnn_lr_joint},
        ])

    # --- Replay buffer ---
    buffer = PrioritizedReplayBuffer(capacity=replay_capacity)

    # --- Training loop ---
    rng = np.random.default_rng(seed)
    global_step = 0
    history = {"episode_reward": [], "episode_delivered": [], "episode_dropped": [], "epsilon": []}
    best_avg_reward = -float("inf")

    ckpt_path = Path(checkpoint_dir)
    ckpt_path.mkdir(parents=True, exist_ok=True)
    tag = "frozen" if freeze_gnn else "joint"
    best_dqn_path = ckpt_path / f"dqn_best_{tag}_{grid_size}x{grid_size}.pt"

    start_time = time.time()

    for episode in range(episodes):
        # Epsilon schedule (linear decay)
        eps = max(eps_end, eps_start - (eps_start - eps_end) * global_step / max(1, eps_decay_steps))

        # Fresh torus + traffic
        ep_seed = seed + episode * 7
        torus = TorusGraph(grid_size)

        # Occasionally inject failures
        if rng.random() < 0.2:
            torus.inject_link_failures(rng.uniform(0.02, 0.1), np.random.default_rng(ep_seed))

        # Generate a batch of packets
        traffic_gen = TrafficGenerator(
            pattern="uniform" if rng.random() < 0.5 else "hotspot",
            grid_size=grid_size,
            injection_rate=injection_rate,
            seed=ep_seed,
        )

        # Get graph state tensors
        state = torus.get_graph_state()
        node_features = torch.tensor(state["node_features"], dtype=torch.float32, device=device)
        edge_index = torch.tensor(state["edge_index"], dtype=torch.long, device=device)
        coord_to_idx = state["coord_to_idx"]

        # Pre-compute embeddings for this episode
        if freeze_gnn:
            with torch.no_grad():
                embeddings = gnn_encoder(node_features, edge_index)
        else:
            embeddings = gnn_encoder(node_features, edge_index)

        # Generate packets for this episode
        from src.sim.packet import Packet
        num_packets = max(5, int(sim_duration_ns * injection_rate))
        packets = []
        active_nodes = torus.get_active_nodes()
        for p_idx in range(num_packets):
            pair = rng.choice(len(active_nodes), size=2, replace=False)
            src = active_nodes[pair[0]]
            dst = active_nodes[pair[1]]
            packets.append(Packet(id=p_idx, src=src, dst=dst, creation_time=0.0))

        episode_reward = 0.0
        ep_delivered = 0
        ep_dropped = 0

        # Route each packet through the torus (simplified RL loop — no SimPy)
        for packet in packets:
            current = packet.src
            packet.record_hop(current)
            max_hops = 4 * grid_size

            for hop_idx in range(max_hops):
                if current == packet.dst:
                    ep_delivered += 1
                    # Terminal state reward
                    reward = _compute_reward(True, False, 0, 0, 0, alpha_drop, beta_util)
                    # Store terminal transition
                    s_vec, _ = _build_dqn_state(
                        gnn_encoder, node_features, edge_index,
                        coord_to_idx[current], packet.src, packet.dst,
                        packet.hops_so_far, grid_size, device, embeddings,
                    )
                    buffer.push(s_vec.cpu().numpy(), 0, reward, s_vec.cpu().numpy(), True)
                    episode_reward += reward
                    break

                # Build state
                s_vec, _ = _build_dqn_state(
                    gnn_encoder, node_features, edge_index,
                    coord_to_idx[current], packet.src, packet.dst,
                    packet.hops_so_far, grid_size, device, embeddings,
                )

                # Select action (epsilon-greedy)
                action = policy_net.select_action(s_vec, epsilon=eps)
                direction = ACTION_TO_DIRECTION[action]

                # Execute action
                done = False
                if direction == "HOLD":
                    # Hold — stay, small penalty
                    next_node = current
                    hop_delay = 1.0
                    packet.consecutive_holds += 1
                    if packet.consecutive_holds > 3:
                        # Forced drop after too many holds
                        packet.mark_dropped("excessive_holds")
                        done = True
                else:
                    next_node = torus.get_neighbor(current, direction)
                    link = torus.get_link(current, next_node)
                    packet.consecutive_holds = 0

                    if link and not link.is_failed and not torus.nodes[next_node].is_failed:
                        hop_delay = link.total_delay_ns
                        # Track utilisation
                        prev_util = link.utilisation
                        link.transmit(packet.payload_size)
                        curr_util = link.utilisation

                        packet.record_hop(next_node)
                        current = next_node
                    else:
                        # Invalid move → drop
                        packet.mark_dropped("invalid_action")
                        done = True
                        hop_delay = 0
                        prev_util = 0
                        curr_util = 0

                delivered_now = (current == packet.dst)
                dropped_now = packet.dropped

                if delivered_now:
                    ep_delivered += 1
                    done = True
                if dropped_now:
                    ep_dropped += 1
                    done = True

                prev_util_val = prev_util if direction != "HOLD" else 0
                curr_util_val = curr_util if direction != "HOLD" else 0

                reward = _compute_reward(
                    delivered_now, dropped_now, hop_delay,
                    prev_util_val, curr_util_val, alpha_drop, beta_util,
                )
                episode_reward += reward

                # Build next state
                s_next, _ = _build_dqn_state(
                    gnn_encoder, node_features, edge_index,
                    coord_to_idx[current], packet.src, packet.dst,
                    packet.hops_so_far, grid_size, device, embeddings,
                )

                # Store transition
                buffer.push(
                    s_vec.cpu().detach().numpy(),
                    action,
                    reward,
                    s_next.cpu().detach().numpy(),
                    done,
                )

                global_step += 1

                # --- DQN update ---
                if len(buffer) >= batch_size:
                    states_b, actions_b, rewards_b, next_states_b, dones_b, indices_b, weights_b = \
                        buffer.sample_tensors(batch_size, device)

                    # Current Q-values
                    q_current = policy_net(states_b).gather(1, actions_b.unsqueeze(1)).squeeze(1)

                    # Target Q-values (Double DQN: use policy net for action selection)
                    with torch.no_grad():
                        next_actions = policy_net(next_states_b).argmax(dim=1)
                        q_next = target_net(next_states_b).gather(1, next_actions.unsqueeze(1)).squeeze(1)
                        q_target = rewards_b + gamma * q_next * (1 - dones_b)

                    # Weighted Huber loss (PER importance sampling)
                    td_errors = q_current - q_target
                    loss = (weights_b * torch.nn.functional.huber_loss(
                        q_current, q_target, reduction="none"
                    )).mean()

                    optimizer.zero_grad()
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(policy_net.parameters(), max_norm=1.0)
                    if not freeze_gnn:
                        torch.nn.utils.clip_grad_norm_(gnn_encoder.parameters(), max_norm=0.5)
                    optimizer.step()

                    # Update priorities
                    buffer.update_priorities(indices_b, td_errors.abs().cpu().detach().numpy())

                    # Target network update
                    if global_step % target_update_freq == 0:
                        target_net.load_state_dict(policy_net.state_dict())

                    # Re-compute embeddings for joint training
                    if not freeze_gnn and global_step % 50 == 0:
                        embeddings = gnn_encoder(node_features, edge_index)

                if done:
                    break

            # Handle packets that didn't reach destination within max_hops
            if not packet.delivered and not packet.dropped:
                ep_dropped += 1

        # Episode logging
        history["episode_reward"].append(episode_reward)
        history["episode_delivered"].append(ep_delivered)
        history["episode_dropped"].append(ep_dropped)
        history["epsilon"].append(eps)

        if writer:
            writer.add_scalar("Reward/episode", episode_reward, episode)
            writer.add_scalar("Delivered/episode", ep_delivered, episode)
            writer.add_scalar("Dropped/episode", ep_dropped, episode)
            writer.add_scalar("Epsilon", eps, episode)

        # Running average for best model selection
        window = min(50, len(history["episode_reward"]))
        avg_reward = np.mean(history["episode_reward"][-window:])

        if avg_reward > best_avg_reward and episode >= 20:
            best_avg_reward = avg_reward
            torch.save({
                "model_state_dict": policy_net.state_dict(),
                "episode": episode,
                "avg_reward": avg_reward,
                "config": {"state_dim": state_dim, "action_dim": action_dim},
            }, best_dqn_path)
            # Also save GNN if joint training
            if not freeze_gnn:
                gnn_joint_path = ckpt_path / f"gnn_joint_{grid_size}x{grid_size}.pt"
                torch.save({
                    "model_state_dict": gnn_encoder.state_dict(),
                    "config": {
                        "in_channels": 8, "hidden_channels": 128,
                        "embedding_dim": embedding_dim, "num_layers": 3,
                    },
                }, gnn_joint_path)

        if (episode + 1) % 50 == 0 or episode == 0:
            logger.info(
                f"Episode {episode+1:4d}/{episodes}: "
                f"reward={episode_reward:.2f}, "
                f"delivered={ep_delivered}, dropped={ep_dropped}, "
                f"eps={eps:.3f}, avg_reward={avg_reward:.2f}, "
                f"buffer={len(buffer)}"
            )

    elapsed = time.time() - start_time

    if writer:
        writer.close()

    logger.info(
        f"DQN training ({mode_str}) complete in {elapsed:.1f}s: "
        f"best_avg_reward={best_avg_reward:.2f}, "
        f"steps={global_step}"
    )

    return {
        "best_avg_reward": best_avg_reward,
        "total_episodes": episodes,
        "total_steps": global_step,
        "training_time_s": elapsed,
        "checkpoint_path": str(best_dqn_path),
        "mode": mode_str,
        "history": history,
    }
